[package]
name = "slides"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stdweb = "0.4.20"
yew = "0.19.3"
yew-router = "0.16"
wasm-bindgen = "0.2.83"
weblog = "0.3.0"
web-sys = "0.3.60"
